### ISSUE TITLE
你这实现完全就算1024Bytes版的xmodem啊，哪是什么ymodem

### ISSUE THREAD

**Issue by yulincoder** [alexwoo1900/ymodem#1]
作者你好，给你反馈几个问题
1. ymodem的header是128B，必须包含文件大小
2. 最后一帧没做处理，直接按照1024处理了
3. header帧处理错误

总结就是根本无法实现ymodem功能。

**Comment by alexwoo1900** [comment]
是的，你说的没错，这不是严格的ymodem协议。

这套代码一开始是以严格的ymodem协议实现，用以我司特定业务。后来发现该业务对接方所使用的逻辑是经过人为修改的xmodem协议，所以最终呈现出的是一个类ymodem的代码。

给你造成疑惑和困扰，深感抱歉。

**Comment by alexwoo1900** [comment]
刚更新了ymodem的实现，感谢你的反馈
