### ISSUE TITLE
How is best to install this package?

### ISSUE THREAD

**Issue by alexwhittemore** [alexwoo1900/ymodem#14]
I notice this package isn't on pypi and also doesn't come with a setup.py file. What's the best strategy to install it locally to try it out?

**Comment by alexwoo1900** [comment]
Use 'pip install -e .' or  manually move the ymodem folder to your project.

**Comment by alexwhittemore** [comment]
Neither of those actually worked for me, hence the question. `pip install -e` fails with no setup.py present, and without installation, the various modules don't even seem to know where to look for each other.

I did figure out though that adding the necessary setup.py was quite easy:

``` python
from setuptools import setup, find_packages

setup(
    name='ymodem',
    version='0.1',
    packages=find_packages()
)
```
That did the trick, and now `setup.py develop` and thus `pip install -e` work.

Is that file present on your system and just not in the repo?

**Comment by alexw-im** [comment]
With fresh eyes I realized where I was going wrong. I read the post below and realized I had out-of-date `setuptools` and `pip`.

The CORRECT solution was not to add a setup.py, but rather `pip install --upgrade pip`, `pip install --upgrade setuptools`, and THEN I was able to properly `pip install -e ~/ymodem`

https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml

**Comment by alexwhittemore** [comment]
With fresh eyes I realized where I was going wrong. I read the post below and realized I had out-of-date setuptools and pip.

The CORRECT solution was not to add a setup.py, but rather pip install --upgrade pip, pip install --upgrade setuptools, and THEN I was able to properly pip install -e ~/ymodem

https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml
