### ISSUE TITLE
Sender EOT issue

### ISSUE THREAD

**Issue by o-murphy** [alexwoo1900/ymodem#18]
The library has an issue with ymodem protocol compatibility (it's about how the sender approves the EOT)

The ymodem protocol requires 2 time approvement off EOT

It have been kinda:
```
# this is the reference

Sender: -> EOT (initial EOT char)
Sender: <- read_and_wait for NAK
Sender: -> EOT (second EOT char)
Sender: <- read_and_wait for ACK


# there the transmitting completely done
# btw some receivers sends additional packet with 'C' char after an EOT complete, and also returns additional packet with filename and filesize back to the sender. And not complete the transmission if that packets have not an answer from sender

# so the minimal reference might look kinda:

Sender: -> EOT (initial EOT char)
Sender: <- read_and_wait for NAK
Sender: -> EOT (second EOT char)
Sender: <- read_and_wait for ACK
Sender: <- read_and_wait for CRC

```

Now I can't find why some receivers are not close the transmittion without that steps. But I already have a fix for that
I tested it and it completely works with my receiver and also with the Hyperterminal on it's receiver mode

The block of the code that have to be modified

```python

'''
                2. YMODEM MINIMUM REQUIREMENTS

                + At the end of each file, the sending program shall send EOT up to ten
                times until it receives an ACK character. (This is part of the
                XMODEM spec.)

                7.3.3 Sending_program_considerations

                When the sender has no more data, it sends an <eot>, and awaits an <ack>,
                resending the <eot> if it doesn't get one. Again, the protocol could be
                receiver-driven, with the sender only having the high-level 1-minute
                timeout to abort.
                '''

                '''
                Some receivers are waiting for EOT twice:
                
                [Sender]: <- ACK
                [Sender]: Reached EOF
                [Sender]: EOT ->
                [Sender]: <- ACK
                '''

                retries = 0
                while True:
                    if retries < 10:
                        # c = self._write_and_wait(EOT, [ACK])
                        c = self._write_and_wait(EOT, [NAK, ACK])
                        self.logger.debug("[Sender]: EOT ->")

                        if c:

                            if c == NAK:
                                self.logger.debug("[Sender]: <- NAK")

                            elif c == ACK:
                                self.logger.debug("[Sender]: <- ACK")
                                break

                            else:
                                self.logger.warning("[Sender]: No ACK or NAK from Receiver, preparing to retransmit.")
                                retries += 1

                        else:
                            self.logger.warning("[Sender]: No ACK or NAK from Receiver, preparing to retransmit.")
                            retries += 1

                    else:
                        self.logger.error(
                            "[Sender]: The number of retransmissions has reached the maximum limit, abort and exit!")
                        self._abort()
                        return False

                '''
                Some receivers are sending CRC after EOT:
                
                [Sender]: <- ACK
                [Sender]: Reached EOF
                [Sender]: EOT ->
                [Sender]: <- ACK
                '''

                retries = 0
                while True:
                    if retries < 10:
                        c = self._read_and_wait([CRC])

                        if c:
                            self.logger.debug(
                                "[Sender]: <- CRC"
                            )
                            break
                        else:
                            self.logger.debug(c)
                            retries += 1
                    else:
                        self.logger.error(
                            "[Sender]: The number of retransmissions has reached the maximum limit, abort and exit!")
                        self._abort()
                        return False


```

**Comment by alexwoo1900** [comment]
emm... @otscher explained the reason in PR #11, I think it's a misreading of protocol standards. Some people consider error examples as necessary steps to take. This is also the reason why some software, although implementing the ymodem protocol, cannot communicate with each other. 

So it is generally recommended that developers make slight modifications to the code based on their own situation. Of course, compatibility code can also be merged here, but complete information or PR of the software interacting with it needs to be provided

**Comment by alexwoo1900** [comment]
Need more informations about these receiver.

**Comment by o-murphy** [comment]
> Need more informations about these receivers.

Double confirmation of EOT is regulated in the description of the [ymodem protocol](http://www.blunk-electronic.de/train-z/pdf/xymodem.pdf) 
* YMODEM Batch Transmission Session (1 file) - page 16
* YMODEM  Batch Transmission Session (multiple files) - page 17

The SOH packet also reglamented in the protocol for confirm the transaction complete after EOT-NAK-EOT-ACK

For example [HyperTerminal](https://ru.wikipedia.org/wiki/HyperTerminal) requires to get EOT twice to complete transmission in receiver mode, also it uses this scheme to send files to target device

I have few devices from third party manufacturer, that uses ymodem protocol to update it's fpga and risc'v firmware
Before I uses HyperTerminal for this task and it works fine, but now I tried to make automated commandline tool for this case, so i found that devices are not starting to flash firmware after uploading the file over ymodem until the CRC packet was not received, and if it isn't happen in some timeout - device returncs CAN

**Comment by o-murphy** [comment]
So I think "EOT-NAK-EOT-ACK-SOH" scheme is required because of matching protocol description

About additional CRC - maybe you're right, and it's unique case

**Comment by otscher** [comment]
Hi,
first, I think this protocol reference is very poorly written, misleading and ambiguous. But then, it is over 40 years old and still in use today. :-)

In my opinion, the data flows in figure 3 and 4 on page 16 and 17 are just  examples that should illustrate what is written on page 22
> When the sender has no more data, it sends an <eot>, and awaits an <ack>,
resending the <eot> if it doesn't get one.
So if the receiver sends anything other than ACK, e.g. due to line noise, the sender repeats the EOT until it gets ACKed.

There is no other explanation of this double EOT inside the whole document, except these two examples figure 3 and 4. If it would be _required_ that the receiver has to NAK the first EOT, I would expect that this would have been clearly highlighted in the text somewhere.

> For example [HyperTerminal](https://ru.wikipedia.org/wiki/HyperTerminal) requires to get EOT twice to complete transmission in receiver mode, also it uses this scheme to send files to target device

I don't see the problem here. If HyperTerminal as the receiver sends a NAK after the EOT, the EOT should just be repeated and HT is happy, or am I missing something?

**Comment by o-murphy** [comment]
> Hi, first, I think this protocol reference is very poorly written, misleading and ambiguous. But then, it is over 40 years old and still in use today. :-)
> 
> In my opinion, the data flows in figure 3 and 4 on page 16 and 17 are just examples that should illustrate what is written on page 22
> 
> > When the sender has no more data, it sends an eot, and awaits an ack, resending the eot if it doesn't get one.
> 
> So if the receiver sends anything other than ACK, e.g. due to line noise, the sender repeats the EOT until it gets ACKed.
> 
> There is no other explanation of this double EOT inside the whole document, except these two examples figure 3 and 4. If it would be _required_ that the receiver has to NAK the first EOT, I would expect that this would have been clearly highlighted in the text somewhere.
> 
> > For example [HyperTerminal](https://ru.wikipedia.org/wiki/HyperTerminal) requires to get EOT twice to complete transmission in receiver mode, also it uses this scheme to send files to target device
> 
> I don't see the problem here. If HyperTerminal as the receiver sends a NAK after the EOT, the EOT should just be repeated and HT is happy, or am I missing something?

I have to recheck it again when I'll have time to return to this project
