### ISSUE TITLE
Unrequested response

### ISSUE THREAD

**Issue by o-murphy** [alexwoo1900/ymodem#20]
Log is 

```
[Receiver]: CRC ->
[Receiver]: CRC ->
[Receiver]: CRC ->
[Receiver]: CRC ->
[Receiver]: CRC ->
[Receiver]: CRC ->
[Receiver]: CRC ->
```

![image](https://github.com/alexwoo1900/ymodem/assets/73843436/0e0afc36-ab46-4f16-a5d7-c5291a56e3dc)

**Comment by alexwoo1900** [comment]
It seems that there is an issue with the interaction between your testing software and the program. Further information is needed, such as details from the serial port debugging.

**Comment by o-murphy** [comment]
> Здається, виникла проблема із взаємодією між вашим тестовим програмним забезпеченням і програмою. Потрібна додаткова інформація, наприклад деталі налагодження послідовного порту.

it happen independent on using QtSerialPort or pyserial


```python
import logging
import sys
from typing import Union, Optional

from qtpy.QtWidgets import QApplication
from qtpy import QtSerialPort
from ymodem.Protocol import ProtocolType
from ymodem.Socket import ModemSocket

logging.basicConfig(level=logging.DEBUG, format='%(message)s')


def main():
    app = QApplication(sys.argv)

    port_name = 'COM5'

    ports = QtSerialPort.QSerialPortInfo.availablePorts()
    port = list(filter(lambda p: p.portName() == port_name, ports))[0]
    port = QtSerialPort.QSerialPort(port)
    port.setBaudRate(115200)

    def write(data: Union[bytes, bytearray], timeout: Optional[float] = 1):
        retval = port.write(data)
        port.flush()
        app.processEvents()
        return retval

    def read(size: int, timeout: Optional[float] = 1):
        buf = bytearray(size)
        bytes_read = port.read(buf, size)
        app.processEvents()
        return buf

    socket = ModemSocket(
        read=read,
        write=write,
        protocol_type=ProtocolType.YMODEM,
        packet_size=1024,
    )
    socket.recv("test.bin")
    # socket.send(["test.bin"])

    app.exec()


if __name__ == '__main__':
    main()

```

**Comment by o-murphy** [comment]
I used the virtual com port driver with a pair of com ports, to monitor the connection, and

**Comment by alexwoo1900** [comment]
I tested your code and rewrited a little bit to fit my env(PyQt for qtpy). Transmission done.

A wrong recv parameter would lead to recving problem.

`import logging
import sys
from typing import Union, Optional

from qtpy.QtCore import QIODevice
from qtpy.QtWidgets import QApplication
from qtpy import QtSerialPort
from ymodem.Protocol import ProtocolType
from ymodem.Socket import ModemSocket

logging.basicConfig(level=logging.DEBUG, format='%(message)s')


def main():
    app = QApplication(sys.argv)

    port_name = 'COM1'

    ports = QtSerialPort.QSerialPortInfo.availablePorts()
    port = list(filter(lambda p: p.portName() == port_name, ports))[0]
    port = QtSerialPort.QSerialPort(port)
    port.setBaudRate(115200)
    port.open(QIODevice.ReadWrite)

    def write(data: Union[bytes, bytearray], timeout: Optional[float] = 1):
        retval = port.write(data)
        port.flush()
        app.processEvents()
        return retval

    def read(size: int, timeout: Optional[float] = 1):
        buf = port.read(size)
        app.processEvents()
        return buf

    socket = ModemSocket(
        read=read,
        write=write,
        protocol_type=ProtocolType.YMODEM,
        packet_size=1024,
    )

   # save folder name
    socket.recv("save")

    app.exec()


if __name__ == '__main__':
    main()`

**Comment by o-murphy** [comment]
@alexwoo1900 

Wow, I didn't know that. You have to add the Warning message or throw the error on this.

**Comment by alexwoo1900** [comment]
In my test with your code, all is well.

Can you repost your log and mark the procedure? I'm not very clear about your interaction process.

PS. After resolving the issue, the API description will be updated.

**Comment by o-murphy** [comment]
> In my test with your code, all is well.
> 
> Can you repost your log and mark the procedure? I'm not very clear about your interaction process.
> 
> PS. After resolving the issue, the API description will be updated.

Can you tell me why u use `buf = port.read(size)` if signature of port.read method requires two arguments `buf: bytearray` and `size: int` ?
I uses PySide6 instead of PyQt

**Comment by o-murphy** [comment]
> ```python
> import logging
> import sys
> from typing import Union, Optional
> 
> from qtpy.QtCore import QIODevice
> from qtpy.QtWidgets import QApplication
> from qtpy import QtSerialPort
> from ymodem.Protocol import ProtocolType
> from ymodem.Socket import ModemSocket
> 
> logging.basicConfig(level=logging.DEBUG, format='%(message)s')
> 
> def main():
>     app = QApplication(sys.argv)
> 
>     port_name = 'COM1'
> 
>     ports = QtSerialPort.QSerialPortInfo.availablePorts()
>     port = list(filter(lambda p: p.portName() == port_name, ports))[0]
>     port = QtSerialPort.QSerialPort(port)
>     port.setBaudRate(115200)
>     port.open(QIODevice.ReadWrite)
> 
>     def write(data: Union[bytes, bytearray], timeout: Optional[float] = 1):
>         retval = port.write(data)
>         port.flush()
>         app.processEvents()
>         return retval
> 
>     def read(size: int, timeout: Optional[float] = 1):
>         buf = port.read(size)
>         app.processEvents()
>         return buf
> 
>     socket = ModemSocket(
>         read=read,
>         write=write,
>         protocol_type=ProtocolType.YMODEM,
>         packet_size=1024,
>     )
> 
>    # save folder name
>     socket.recv("save")
> 
>     app.exec()
> 
> if __name__ == '__main__':
>     main()
> ```

I got the save working good with this snippet

```
import logging
import sys
from typing import Union, Optional

from qtpy.QtCore import QIODevice
from qtpy.QtWidgets import QApplication
from qtpy import QtSerialPort
from ymodem.Protocol import ProtocolType
from ymodem.Socket import ModemSocket

logging.basicConfig(level=logging.DEBUG, format='%(message)s')

def main():
    app = QApplication(sys.argv)

    port_name = 'COM2'

    ports = QtSerialPort.QSerialPortInfo.availablePorts()
    port = list(filter(lambda p: p.portName() == port_name, ports))[0]
    port = QtSerialPort.QSerialPort(port)
    port.setBaudRate(115200)
    port.open(QtSerialPort.QSerialPort.OpenModeFlag.ReadWrite)
    # port.open(QIODevice.ReadWrite)

    def write(data: Union[bytes, bytearray], timeout: Optional[float] = 1):
        retval = port.write(data)
        port.flush()
        app.processEvents()
        return retval

    def read(size: int, timeout: Optional[float] = 1):
        buf = bytearray(size)
        ret = port.read(buf, size)
        # print(buf)
        app.processEvents()
        return bytes(buf)

    socket = ModemSocket(
        read=read,
        write=write,
        protocol_type=ProtocolType.YMODEM,
        packet_size=1024,
    )

    # save folder name
    # socket.recv("save")
    socket.send(["test.bin"])

    app.exec()


if __name__ == '__main__':
    main()
```

But it fails on send here

```
Socket.py", line 553, in recv
    task.mtime = int(data if space_index == -1 else data[:space_index], 8)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 8: '430682'
```

**Comment by o-murphy** [comment]
I used the same file to send and receive

**Comment by o-murphy** [comment]
> But it fails on send here
> 
> ```python
> Socket.py", line 553, in recv
>     task.mtime = int(data if space_index == -1 else data[:space_index], 8)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: invalid literal for int() with base 8: '430682'
> ```

It can be fixed by changing int base to 16

task.mtime = int(data if space_index == -1 else data[:space_index], 16)

**Comment by alexwoo1900** [comment]
> > In my test with your code, all is well.
> > Can you repost your log and mark the procedure? I'm not very clear about your interaction process.
> > PS. After resolving the issue, the API description will be updated.
> 
> Can you tell me why u use `buf = port.read(size)` if signature of port.read method requires two arguments `buf: bytearray` and `size: int` ? I uses PySide6 instead of PyQt

PySide6 supports two signatures of read() but PyQt6 only supports one. There are differences in their implementation of QIODevice.

**Comment by alexwoo1900** [comment]
> > But it fails on send here
> > ```python
> > Socket.py", line 553, in recv
> >     task.mtime = int(data if space_index == -1 else data[:space_index], 8)
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ValueError: invalid literal for int() with base 8: '430682'
> > ```
> 
> It can be fixed by changing int base to 16
> 
> task.mtime = int(data if space_index == -1 else data[:space_index], 16)

This should not have happened. The message indicates that data parsing has been misplaced, 430682 should be the length of the data rather than mtime. 

This seems like the sender and receiver are using different styles of ymodem. The sender carries length data, while the receiver ignores it.

**Comment by o-murphy** [comment]
> This should not have happened. The message indicates that data parsing has been misplaced, 430682 should be the length of the data rather than mtime.
> 
> This seems like the sender and receiver are using different styles of ymodem. The sender carries length data, while the receiver ignores it.

how can I specify the option to strong usage of "length" instead of "mtime"

**Comment by alexwoo1900** [comment]
> > This should not have happened. The message indicates that data parsing has been misplaced, 430682 should be the length of the data rather than mtime.
> > This seems like the sender and receiver are using different styles of ymodem. The sender carries length data, while the receiver ignores it.
> 
> how can I specify the option to avoid usage of "mtime" instead of "length"?

All protocol styles manage by class ProtocolStyleManagement in Protocol.py, but usually you don't need to modify it.

I suggest you print out the data section according to the parsing steps to determine why this error occurred.

**Comment by alexwoo1900** [comment]
No more information
