### ISSUE TITLE
ymodem没有实现对Final packet的处理

### ISSUE THREAD

**Issue by DazzlingOkami** [alexwoo1900/ymodem#5]
这个ymodem还不支持批量文件传输，关键是传输单个文件时也没有在文件传输的结尾传输SOH的空包。
这个程序自己收发没有问题，但是不能和其它程序兼容。

**Comment by alexwoo1900** [comment]
1. ymodem还不支持批量文件传输，没错。
2. 有传输空包。
3. 可以与其它程序兼容，比如SecureCRT，README里面有截图。
