### ISSUE TITLE
Modem接受bug

### ISSUE THREAD

**Issue by legendaryzp** [alexwoo1900/ymodem#6]
modem.py 的567行
data = self.reader.read(packet_size + 1 + crc_mode, timeout)
 valid, data = self._verify_recv_checksum(crc_mode, data)

其中data 不能保证接受成功啊，得加个校验语句，以保证后面不出错。
if data and len(data)>=2:
（说多了都是泪）

**Comment by alexwoo1900** [comment]
有没有case详情，你直接提PR，我合并进去

**Comment by alexwoo1900** [comment]
fixed
