### ISSUE TITLE
使用ymodem进行传输，128bytes传输不成功，1024bytes传输成功，使用crt软件128bytes和1024bytes都能传输成功

### ISSUE THREAD

**Issue by yincheng8** [alexwoo1900/ymodem#7]
[Sender]: Reached EOF
[Sender]: EOT sent and awaiting NAK
[Sender]: Error, expected NAK but got b'\x06'
[Sender]: Error, expected NAK but got b'C'

**Comment by yincheng8** [comment]
使用两个虚拟串口128和1024都能成功，代码切换到实际应用后，128就会传输失败。

**Comment by alexwoo1900** [comment]
你的实际应用是什么

**Comment by alexwoo1900** [comment]
没有后续详情
